programme: qubit.cpp matrice.cpp fonctions.cpp main.cpp
	g++ -Wall -std=c++17 -o programme qubit.cpp matrice.cpp constants.cpp fonctions.cpp main.cpp

clean:
	rm -f *~ *.o  # Also remove object files

mrproper: clean
	rm -f programme
