programme: qubit_system.cpp qubit.cpp tens_2q.cpp tens_Nq.cpp matrice.cpp main.cpp
	g++ -Wall -std=c++17 -o programme qubit_system.cpp qubit.cpp tens_2q.cpp tens_Nq.cpp matrice.cpp main.cpp

clean:
	rm -f *~

mrproper: clean
	rm -f programme